# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a23bc75b695ccbec85264be5d1980da0055d4d07b5a98a90e0a028c76c605b99bbc510ecb4c82d6e314cf75f52c62f8be11c88abc191eae0c95100996b59ada

test:
  secret_key_base: 8c29c478eecde3325ffb521f9ebc3dc0e26bea0a871fae9b1b29d96d43caa653224f414dffda4a6e6898e52b1287d228bc10a9e0e3bad80c8779bfe76a31739a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
